---
title: "Assignment 1: Introduction"
author: "Brianna Karson"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.

7.  Initial here to acknowledge that you did not use AI at all in completing this assignment: BK

---

## 1) Concept and Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 

> __R experience:__ In undergrad, I took a Biometry class that served as an intro to R, modeling, and data analytics. For my final project, I remember using a model to assess coral reef survey data. The following year, I completed a (year-long) independent thesis project where I meta-analyzed case studies using R. 

> __Data analytics experience:__ Aside from the above, I have done some minor data analytics in my managerial role at Avasol, a reef-safe, organic sunscreen company. I use excel to analyze sales and inventory data for trends each year. I also am currently a Research Assistant in the Ocean Synthesis Lab, where I have been learning how to do thematic coding and qualitative analyses. I also have 2 courses worth of GIS experience under my belt (will be 4 by the end of the semester) if that counts as data analytics!  

> __Git:__ None! It has been the most confusing part of the class so far. 

2. Are there any components of the course about which you feel confident?

> Answer: 
>By the time I finished undergrad I felt pretty confident in my (albeit limited) R skills, but it's been a 5 years since then, with basically no practice. I do feel confident that once I am back in the swing of things I will be able to navigate R well, and am looking forward to continuing to develop this skill. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
>When I learned R the first time I remember it being really frustrating and time-consuming. The learning curve is definitely tough but I know that it is worth it! 

4. Describe a dataset you have used in the past. Explain whether it was a primary or secondary dataset. 

> Answer: 
>For the senior thesis I described above, I followed an existing, standardized protocol to evaluate a group of around 20 detailed case studies. Each study received a score of 0-3 for a number of variables related to ecological effectiveness, community involvement, etc (there were around 30 different categories). Then, these categorical scores were used to calculate % scores to represent how successful each case study was socially, ecologically, and overall. Afterwards, this data was used to run a meta-analysis of all the evaluated case studies. This would be considered primary data because I personally conducted the evaluation that yielded the scores and %s. 

5. Would you describe the day of the month as a nominal, ordinal, interval, or ratio number? Explain your reasoning.

> Answer: 
>I think that days of the month would best be described as interval numbers since they have a known order and a occur at a set interval of 24hrs/day (thus eliminating ordinal as an option). Since there is no zero value for days of the month, they cannot be described as being ratio numbers. Days of the month do not represent categories, so they are not nominal. 

---

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 
> https://github.com/brianna-karson/EDE_Spring2026
---

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
